[package]
name = "arcslab"
version = "0.1.0"
edition = "2021"
description = "Slab, but with reference counted items"
license = "MIT OR Apache-2.0"

[dependencies]

# strict provenance polyfill
# (TODO: remove this once the `strict_provenance` feature becomes stable)
sptr = "0.3"

# fast alternative Mutex & RwLock implementation
parking_lot = "0.12"

# `CachePadded`
crossbeam-utils = { version = "0.8", default-features = false }

[target.'cfg(all(not(miri), target_os = "linux"))'.dependencies]
# `madvise`
rustix = { version = "0.38", features = ["mm"], default-features = false }
