name: Pipeline

# spell-checker:ignore dtolnay

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        components: clippy, rustfmt
    - uses: extractions/setup-just@v1
    - name: Install cSpell
      run: npm install --prefix=.local/cspell -g cspell
    - name: Lint
      run: just lint
    - name: Doc
      run: cargo doc --no-deps
      env:
        RUSTDOCFLAGS: "-D warnings"

  test:
    name: Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: ['stable', 'nightly']
        flags: ['', '--release']

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
    - name: Build
      run: cargo build ${{ matrix.flags }} --verbose
      env:
        RUSTFLAGS: "-D warnings"
    - name: Run Tests
      run: cargo test ${{ matrix.flags }} --verbose
