name: Spell Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  spellcheck:
    name: Spell Check

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: streetsidesoftware/cspell-action@v6
      with:
        check_dot_files: true
        use_cspell_files: true
