name: Spell Check

on: [push]

jobs:
  spellcheck:
    name: Spell Check

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v5
    - uses: streetsidesoftware/cspell-action@v7
      with:
        check_dot_files: true
        use_cspell_files: true
