name: Spell Check

on: [push]

jobs:
  spellcheck:
    name: Spell Check

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
      - uses: streetsidesoftware/cspell-action@v8
        with:
          check_dot_files: true
          use_cspell_files: true
